---
- name: generate install shell
  shell: |
      cd {{WORKING_DIR}}

      oc adm -a {{LOCAL_SECRET_JSON}} release extract \
         --command=openshift-install \
         "{{LOCAL_REGISTRY}}/{{LOCAL_REPOSITORY}}:{{OCP_RELEASE}}"

      test $(echo $?) -eq 0

- name: generate install-config.yaml
  template:
    src: ./templates/install-config.j2
    dest: ./templates/install-config.yaml

- name: mv to working dir
  shell: mv ./templates/install-config.yaml {{WORKING_DIR}}/install/install-config.yaml