---
- name: create working directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    recurse: yes
  loop:
    - /{{WORKING_DIR}}/clients
    - /{{WORKING_DIR}}/dependencies
    - /{{WORKING_DIR}}/install
    - /{{WORKING_DIR}}/registry/auth
    - /{{WORKING_DIR}}/registry/data
    - /{{WORKING_DIR}}/registry/certs
    - /{{WORKING_DIR}}/registry/images

- name: download openshift client commands
  get_url:
    url: "{{ OCP_CLIENT_CMD_URL }}"
    dest: /{{WORKING_DIR}}/clients/openshift-client-linux.tar.gz

- name: download openshift install commands
  get_url:
    url: "{{ OCP_INSTALL_CMD_URL }}"
    dest: /{{WORKING_DIR}}/clients/openshift-install-linux.tar.gz

- name: uncompress
  shell: tar -zxvf /{{WORKING_DIR}}/clients/openshift-client-linux.tar.gz -C /usr/bin

- name: download rhcos image
  get_url:
    url: "{{ RHCOS_IMAGE_URL }}"
    dest: /{{WORKING_DIR}}/dependencies/rhcos-metal.x86_64.raw.gz

- name: download centos image
  get_url:
    url: "{{ CENTOS_IMAGE_URL }}"
    dest: /{{WORKING_DIR}}/dependencies/centos.iso
