---
# vars file for install
ocp_admin_password: "letmein"

bastion_ip: "172.16.251.242"

ntp_allow: "172.16.251.0/24"

# This should be a real ntp server(public or private), in airgap scenario, fillin the ip of bastion
ntp_servers: 
  - '172.16.251.242'
default_gateway: "172.16.255.250"
# In airgap scenario, fillin the ip of bastion
external_name_servers:
  - '8.8.8.8'
interface_script: "/etc/sysconfig/network-scripts/ifcfg-ens192"

# for IPI
apiVIP: "172.16.251.221"
ingressVIP: "172.16.251.221"
# end for IPI

vm_number_of_masters: 3
vm_number_of_workers: 3

###############################################################################
##########  custom params 
###############################################################################

REGISTRY_NAME: "ocp-install-registry"
HTTPD_LISTEN_PORT: "9080"

pull_secret_file: "{{WORKING_DIR}}/install/ocp_pullsecret.json"

ansible_ssh_common_args: '-o StrictHostKeyChecking: no'

rhcos_installation_method: pxe
vm_create_vms: False
run_install: False

ocp_install_dir: "{{WORKING_DIR}}/dependencies"
openshift_release: "{{OCP_VERSION}}"

#
# Air gapped installation settings
#
air_gapped_install: True
air_gapped_registry_server: "{{REGISTRY_SERVER}}"
air_gapped_source_ocp_release: "quay.io/openshift-release-dev/ocp-release"
air_gapped_mirror_ocp_release: "{{air_gapped_registry_server}}:{{REGISTRY_PORT}}/ocp4/openshift4"
air_gapped_source_ocp_release_dev: "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
air_gapped_mirror_ocp_release_dev: "{{air_gapped_registry_server}}:{{REGISTRY_PORT}}/ocp4/openshift4"
air_gapped_registry_trust_bundle_file: "{{WORKING_DIR}}/registry/certs/registry.crt"


opt_out_health_checking: False

setup_chrony_server: True

override_chrony_settings_on_cluster_nodes: True

dhcp_on_bastion: False
dhcp_range:
  - '192.168.100.41'
  - '192.168.100.50'

manage_load_balancer: True

set_bastion_hostname: True

manage_nfs: True
volume_selector: "sdb"

nfs_volume_mount_path: "/nfs"
mount_point: "/nfs"

create_nfs_sc: True

image_registry_storage_class: nfs-client
image_registry_size: 200Gi

service_network: "172.30.0.0/16"