---
#
# 0. Prepare bastion node
#
- include: disable_firewalld.yaml
# Prepare mirror registry
- include: start_registry.yaml
# Prepare http server with port 9080 for ignition files and others
- include: httpd-server.yaml

#
# 1. Initialize bastion node
#
# have no idea what this task for, todo...
- include: init_facts.yaml

- include: firewall_iptables_remove.yaml
- include: set_hostname.yaml
- include: hosts.yaml
- include: ssh_playbook.yaml


#
# 2. Configure instrastructure services (DNS, DHCP, Chrony, HAProxy, NFS)
#
- include: chrony_server.yaml
- include: chrony_client.yaml

# for ansible
- include: etc_ansible_hosts.yaml
- include: dnsmasq_libvirt_remove.yaml

- include: dns_server.yaml
- include: dns_interface.yaml
- include: haproxy.yaml
- include: prepare_xfs_volume.yaml
- include: nfs_server.yaml

#
# 4. Install OpenShift
#
- include: ocp_install_config.yaml
- include: ocp_ignition.yaml
- include: create_oauth.yaml
- include: registry_storage.yaml
- include: ocp_install_scripts.yaml
